services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_container_user
      - POSTGRES_PASSWORD=test_container_password
      - POSTGRES_PORT=5432
    volumes:
      - data-postgres-test:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_container_user -d test_db"]
      interval: 1s
      timeout: 3s
      retries: 3

  app:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8200 --reload "
    environment:
      DB_NAME: test_db
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: test_container_user
      DB_PASSWORD: test_container_password
      PYTHONPATH: /app
    ports:
      - "8200:8200"
    depends_on:
      - database

volumes:
  data-postgres-test:

networks:
  default:
    name: medicapp_network
