"""Adicionando novo medicamento

Revision ID: 3d90d357bfaf
Revises: 430ac3406c60
Create Date: 2025-03-20 09:50:03.322968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d90d357bfaf'
down_revision: Union[str, None] = '430ac3406c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_drugs', sa.Column('name', sa.String(), nullable=True))
    op.add_column('user_drugs', sa.Column('principio_ativo', sa.String(), nullable=True))
    op.add_column('user_drugs', sa.Column('is_generic', sa.Boolean(), nullable=True))
    op.add_column('user_drugs', sa.Column('brand', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_drugs', 'brand')
    op.drop_column('user_drugs', 'is_generic')
    op.drop_column('user_drugs', 'principio_ativo')
    op.drop_column('user_drugs', 'name')
    # ### end Alembic commands ###
