"""Removendo a coluna de relacionamento de user drugs com drug para teste

Revision ID: 8ea9c195ad60
Revises: 3d90d357bfaf
Create Date: 2025-03-20 12:50:07.865938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea9c195ad60'
down_revision: Union[str, None] = '3d90d357bfaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_drugs_drug_id_fkey', 'user_drugs', type_='foreignkey')
    op.drop_column('user_drugs', 'drug_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_drugs', sa.Column('drug_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_drugs_drug_id_fkey', 'user_drugs', 'drugs', ['drug_id'], ['id'])
    # ### end Alembic commands ###
