"""Revisando logica de UserDrugs

Revision ID: a9e09be58e5a
Revises: 6783466a1873
Create Date: 2025-03-29 17:46:00.918827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9e09be58e5a'
down_revision: Union[str, None] = '6783466a1873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_drugs', sa.Column('concentracao', sa.String(), nullable=True))
    op.drop_column('user_drugs', 'taked')
    op.drop_column('user_drugs', 'total')
    op.drop_column('user_drugs', 'brand')
    op.drop_column('user_drugs', 'is_generic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_drugs', sa.Column('is_generic', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user_drugs', sa.Column('brand', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_drugs', sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_drugs', sa.Column('taked', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user_drugs', 'concentracao')
    # ### end Alembic commands ###
