"""Tabela de Medicamentos completa baseada na lista da anvisa

Revision ID: b5d283988b1d
Revises: f64029ed4222
Create Date: 2025-03-23 02:00:31.400005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5d283988b1d'
down_revision: Union[str, None] = 'f64029ed4222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drugs', sa.Column('farmaco', sa.String(), nullable=False))
    op.add_column('drugs', sa.Column('detentor', sa.String(), nullable=False))
    op.add_column('drugs', sa.Column('medicamento', sa.String(), nullable=False))
    op.add_column('drugs', sa.Column('registro', sa.Integer(), nullable=False))
    op.add_column('drugs', sa.Column('concentracao', sa.String(), nullable=False))
    op.add_column('drugs', sa.Column('forma_farmaceutica', sa.String(), nullable=False))
    op.add_column('drugs', sa.Column('data_inclusao', sa.String(), nullable=False))
    op.drop_column('drugs', 'name')
    op.drop_column('drugs', 'created_at')
    op.drop_column('drugs', 'principio_ativo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drugs', sa.Column('principio_ativo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('drugs', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('drugs', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('drugs', 'data_inclusao')
    op.drop_column('drugs', 'forma_farmaceutica')
    op.drop_column('drugs', 'concentracao')
    op.drop_column('drugs', 'registro')
    op.drop_column('drugs', 'medicamento')
    op.drop_column('drugs', 'detentor')
    op.drop_column('drugs', 'farmaco')
    # ### end Alembic commands ###
