"""escreve aqui o porque

Revision ID: e7294cb189ce
Revises: 8ea9c195ad60
Create Date: 2025-03-23 00:50:21.589900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7294cb189ce'
down_revision: Union[str, None] = '8ea9c195ad60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('principio_ativo1', sa.Integer(), nullable=False),
    sa.Column('principio_ativo2', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interactions')
    # ### end Alembic commands ###
