"""Tabela de interacoes completa

Revision ID: f64029ed4222
Revises: b50e54069c14
Create Date: 2025-03-23 01:45:23.097814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f64029ed4222'
down_revision: Union[str, None] = 'b50e54069c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('gravidade_interacao', sa.String(), nullable=False))
    op.add_column('interactions', sa.Column('inicio_interacao', sa.String(), nullable=False))
    op.add_column('interactions', sa.Column('probabilidade_ocorrencia', sa.String(), nullable=False))
    op.add_column('interactions', sa.Column('efeito', sa.String(), nullable=False))
    op.alter_column('interactions', 'principio_ativo1',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('interactions', 'principio_ativo2',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interactions', 'principio_ativo2',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('interactions', 'principio_ativo1',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('interactions', 'efeito')
    op.drop_column('interactions', 'probabilidade_ocorrencia')
    op.drop_column('interactions', 'inicio_interacao')
    op.drop_column('interactions', 'gravidade_interacao')
    # ### end Alembic commands ###
