name: Docker CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/medic-app-api:latest

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop medic-app-api || true
            docker rm medic-app-api || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/medic-app-api:latest
            docker run -d --env DB_USER=$DB_USER --env DB_PASSWORD=$DB_PASSWORD --env DB_NAME=$DB_NAME --env DB_HOST=$DB_HOST --env DB_PORT=$DB_PORT -p 80:80 --name medic-app-api ${{ secrets.DOCKERHUB_USERNAME }}/medic-app-api:latest
