name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t medicapp-backend ./backend

      - name: Setup SQLite
        uses: actions/setup-sqlite@v1
        with:
          sqlite-version: 3.49.1
          sqlite-year: 2025

      - name: Create Test database
        run: |
          sqlite3 test_db.db \
          "CREATE TABLE IF NOT EXISTS interactions \
          (id INTEGER PRIMARY KEY, \
          gravidade_interacao TEXT, \
          inicio_interacao TEXT, \
          probabilidade_ocorrencia TEXT, \
          efeito TEXT, \
          principio_ativo1 TEXT, \
          principio_ativo2 TEXT);"

      - name: Run tests with pytest
        run: |
          docker run \
            --env DB_USER=${{ secrets.DB_USER }} \
            --env DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --env DB_NAME=${{ secrets.DB_NAME }} \
            --env DB_HOST=${{ secrets.DB_HOST }} \
            --env DB_PORT=${{ secrets.DB_PORT }} \
            --rm medicapp-backend pytest -vvv --disable-pytest-warnings --log-cli-level=INFO
