name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t medicapp-backend ./backend

      - name: Run tests with pytest
        run: |
          docker run --rm medicapp-backend pytest
