name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start API and DB Containers
        run: |
          docker-compose -f backend/docker-compose.test.yml up -d
          sleep 5

      - name: Wait for DB to be ready
        run: |
          for i in {1..10}; do
            if docker exec medicapp-backend-db pg_isready -U test_container_user -d test_db; then
              echo "DB is ready"
              break
            fi
            echo "Waiting for DB to be ready..."
            sleep 5
          done

      - name: Run Tests
        run: |
          docker exec app sh -c "pytest -vvv --disable-pytest-warnings --log-cli-level=INFO"

      - name: Stop API and DB Containers
        run: |
          docker-compose -f backend/docker-compose.test.yml down
          docker volume rm medicapp_network_data-postgres-test

      - name: Remove Docker containers
        run: |
          docker rm -f medicapp-backend medicapp-backend-db
          docker network rm medicapp_network
          docker volume rm medicapp_network_data-postgres-test
