name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Images
        run: |
          docker compose -f backend/docker-compose.test.yml build --no-cache

      - name: Start API and DB Containers
        run: |
          docker compose -f backend/docker-compose.test.yml up --build -d
          sleep 5

      - name: Check Containers Status
        run: |
          docker ps -a

      - name: Check Container Files
        run: |
          docker exec backend-app-1 sh -c "ls -la /app"

      - name: Wait for DB to be ready
        run: |
          for i in {1..10}; do
            if docker exec backend-database-1 pg_isready -U test_container_user -d test_db; then
              echo "DB is ready"
              break
            fi
            echo "Waiting for DB to be ready..."
            sleep 5
          done

      - name: Verify requirements.txt content
        run: |
          docker exec backend-app-1 sh -c "ls -la /app && cat /app/requirements.txt || echo 'requirements.txt not accessible'"

      - name: Install dependencies in chunks
        run: |
          docker exec backend-app-1 sh -c "
          if [ -f /app/requirements.txt ]; then
            for package in $(cat /app/requirements.txt); do
              pip install --no-cache-dir $package || exit 1;
            done
          else
            echo 'requirements.txt not found or not accessible';
            exit 1;
          fi
          "

      - name: Verify dependencies installation
        run: |
          docker exec backend-app-1 sh -c "
          pip show pytest || echo 'pytest is not installed';
          pip show fastapi || echo 'fastapi is not installed';
          pip show sqlalchemy || echo 'sqlalchemy is not installed';
          "

      - name: Run Tests
        run: |
          docker exec backend-app-1 sh -c "pytest -vvv --disable-pytest-warnings --log-cli-level=INFO"

      - name: Stop API and DB Containers
        run: |
          docker compose -f backend/docker-compose.test.yml down

      - name: Remove Docker Volumes
        run: |
          docker volume rm backend_data-postgres-test
