name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t medicapp-backend ./backend

      - name: Run tests with pytest
        run: |
          docker run --env DB_USER=${{ secrets.TEST_DB_USER }} --env DB_PASSWORD=${{ secrets.TEST_DB_PASSWORD }} --env DB_NAME=${{ secrets.TEST_DB_NAME }} --env DB_HOST=${{ secrets.TEST_DB_HOST }} --env DB_PORT=${{ secrets.TEST_DB_PORT }} --rm medicapp-backend pytest
